version: 2

models:
  - name: dim_customers
    description: "the customer dimension"
    columns:
      - name: customer_id
        description: "the primary key for the customers"
        tests:
          - not_null
          - unique
      - name: customer_address
        description: "the address for the customer"
        tests:
          - not_null
      - name: customer_city
        description: "the city for the customer"
        tests:
          - not_null
      - name: customer_state
        description: "the state for the customer"
        tests:
          - not_null
      - name: customer_zip
        description: "the zip code for the customer"
        tests:
          - not_null
          - test_zip_code_validity:
              column_name: customer_zip
              min_zip: 90000
              max_zip: 99999
      - name: customer_region
        description: "the sales region for the customer"
        tests:
          - not_null
      - name: customer_phone
        description: "the telephone number for the customer"
        tests:
          - not_null

  - name: dim_sales_order_headers
    description: "the sales order header dimension"
    columns:
      - name: sales_order_id
        description: "the primary key for the sales order header"
        tests:
          - not_null
          - unique
      - name: customer_id
        description: "the foreign key to the customers"
        tests:
          - not_null
      - name: sales_amount
        description: "the total net sales amount for the entire sales order"
        tests:
          - not_null
      - name: sales_date
        description: "the date of the sales order"
        tests:
          - not_null
      - name: shipping_amount
        description: "the total shipping amount for the sales order"
        tests:
          - not_null
      - name: tax_amount
        description: "the total tax amount for the sales order"
        tests:
          - not_null
          - unique
      - name: total_amount
        description: "the grand total for the entire sales order"

  - name: dim_sales_order_details
    description: "the sales order detail dimension"
    columns:
      - name: sales_order_id
        description: "part of the primary key of the sales order"
        tests:
          - not_null
      - name: sales_order_detail_id
        description: "part of the primary key of the sales order"
        tests:
          - not_null
      - name: product_id
        description: "the product id of the sales order line"
        tests:
          - not_null
      - name: product_price
        description: "the price of the product of the sales order line"
        tests:
          - not_null
      - name: order_quantity
        description: "the quantity of the individual product ordered"
        tests:
          - not_null
      - name: total_price
        description: "the calculated result of the quantity of product prices"
        tests:
          - not_null

  - name: dim_sales_regions
    description: "the sales regions"
    columns:
      - name: sales_region_zip_begin
        description: "the lowest value in the region zip code range"
        tests:
          - not_null
          - unique
      - name: sales_region_zip_end
        description: "the highest value in the region zip code range"
        tests:
          - not_null
          - unique
      - name: sales_region
        description: "the name of the sales region"
        tests:
          - not_null
          - unique
